// Torque Input Map File
moveMap.delete();
new ActionMap(moveMap);
moveMap.bindCmd(keyboard, "escape", "", "escapeFromGame();");
moveMap.bindCmd(keyboard, "f2", "", "PlayerListGui.toggle();");
moveMap.bind(keyboard, "a", moveleft);
moveMap.bind(keyboard, "d", moveright);
moveMap.bind(keyboard, "w", moveforward);
moveMap.bind(keyboard, "s", movebackward);
moveMap.bind(keyboard, "space", jump);
moveMap.bind(keyboard, "z", setZoomFOV);
moveMap.bind(keyboard, "tab", toggleFirstPerson);
moveMap.bindCmd(keyboard, "ctrl k", "commandToServer(\'suicide\');", "");
moveMap.bind(keyboard, "pageup", pageMessageHudUp);
moveMap.bind(keyboard, "pagedown", pageMessageHudDown);
moveMap.bind(keyboard, "p", resizeMessageHud);
moveMap.bind(keyboard, "f3", startRecordingDemo);
moveMap.bind(keyboard, "f4", stopRecordingDemo);
moveMap.bind(keyboard, "f8", dropCameraAtPlayer);
moveMap.bind(keyboard, "f7", dropPlayerAtCamera);
moveMap.bind(keyboard, "f", toggleZoom);
moveMap.bind(keyboard, "lshift", crouch);
moveMap.bind(keyboard, "c", walk);
moveMap.bind(keyboard, "t", toggleMessageHud);
moveMap.bind(keyboard, "left", turnLeft);
moveMap.bind(keyboard, "right", turnRight);
moveMap.bind(keyboard, "up", panUp);
moveMap.bind(keyboard, "down", panDown);
moveMap.bind(keyboard, "lcontrol", toggleFreeLook);
moveMap.bind(keyboard, "1", useFirstSlot);
moveMap.bind(keyboard, "2", useSecondSlot);
moveMap.bind(keyboard, "3", useThirdSlot);
moveMap.bind(keyboard, "4", useFourthSlot);
moveMap.bind(keyboard, "5", useFifthSlot);
moveMap.bind(keyboard, "6", useSixthSlot);
moveMap.bind(keyboard, "7", useSeventhSlot);
moveMap.bind(keyboard, "8", useEighthSlot);
moveMap.bind(keyboard, "9", useNinthSlot);
moveMap.bind(keyboard, "0", useTenthSlot);
moveMap.bind(keyboard, "ctrl 1", dropFirstSlot);
moveMap.bind(keyboard, "ctrl 2", dropSecondSlot);
moveMap.bind(keyboard, "ctrl 3", dropThirdSlot);
moveMap.bind(keyboard, "ctrl 4", dropFourthSlot);
moveMap.bind(keyboard, "ctrl 5", dropFifthSlot);
moveMap.bind(keyboard, "ctrl 6", dropSixthSlot);
moveMap.bind(keyboard, "ctrl 7", dropSeventhSlot);
moveMap.bind(keyboard, "ctrl 8", dropEighthSlot);
moveMap.bind(keyboard, "ctrl 9", dropNinthSlot);
moveMap.bind(keyboard, "ctrl 0", dropTenthSlot);
moveMap.bind(keyboard, "numpad8", shiftBrickAway);
moveMap.bind(keyboard, "numpad2", shiftBrickTowards);
moveMap.bind(keyboard, "numpad4", shiftBrickLeft);
moveMap.bind(keyboard, "numpad9", RotateBrickCW);
moveMap.bind(keyboard, "numpad7", RotateBrickCCW);
moveMap.bind(keyboard, "numpadenter", plantBrick);
moveMap.bind(keyboard, "numpad6", shiftBrickRight);
moveMap.bind(keyboard, "+", shiftBrickUp);
moveMap.bind(keyboard, "numpad5", shiftBrickDown);
moveMap.bind(keyboard, "numpad0", cancelBrick);
moveMap.bind(keyboard, "numpad3", shiftBrickThirdUp);
moveMap.bind(keyboard, "numpad1", shiftBrickThirdDown);
moveMap.bind(keyboard, "ctrl a", openAdminWindow);
moveMap.bind(keyboard, "ctrl o", openOptionsWindow);
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(mouse0, "button1", Jet);
