// Torque Input Map File
moveMap.delete();
new ActionMap(moveMap);
moveMap.bindCmd(keyboard, "escape", "", "escapeFromGame();");
moveMap.bindCmd(keyboard, "f2", "", "PlayerListGui.toggle();");
moveMap.bind(keyboard, "space", jump);
moveMap.bind(keyboard, "tab", toggleFirstPerson);
moveMap.bind(keyboard, "alt c", toggleCamera);
moveMap.bindCmd(keyboard, "ctrl k", "commandToServer(\'suicide\');", "");
moveMap.bind(keyboard, "f3", startRecordingDemo);
moveMap.bind(keyboard, "f4", stopRecordingDemo);
moveMap.bind(keyboard, "f8", dropCameraAtPlayer);
moveMap.bind(keyboard, "f7", dropPlayerAtCamera);
moveMap.bind(keyboard, "ctrl e", openInGameEditor);
moveMap.bind(keyboard, "q", freeze);
moveMap.bind(keyboard, "e", doAction);
moveMap.bind(keyboard, "lalt", togSuperShift);
moveMap.bind(keyboard, "t", toggleMessageHud);
moveMap.bind(keyboard, "y", teamMessageHud);
moveMap.bind(keyboard, "pageup", pageMessageHudUp);
moveMap.bind(keyboard, "pagedown", pageMessageHudDown);
moveMap.bind(keyboard, "p", resizeMessageHud);
moveMap.bind(keyboard, "1", useFirstSlot);
moveMap.bind(keyboard, "2", useSecondSlot);
moveMap.bind(keyboard, "3", useThirdSlot);
moveMap.bind(keyboard, "4", useFourthSlot);
moveMap.bind(keyboard, "5", useFifthSlot);
moveMap.bind(keyboard, "6", useSixthSlot);
moveMap.bind(keyboard, "7", useSeventhSlot);
moveMap.bind(keyboard, "8", useEighthSlot);
moveMap.bind(keyboard, "9", useNinthSlot);
moveMap.bind(keyboard, "0", useTenthSlot);
moveMap.bind(keyboard, "ctrl 1", dropFirstSlot);
moveMap.bind(keyboard, "ctrl 2", dropSecondSlot);
moveMap.bind(keyboard, "ctrl 3", dropThirdSlot);
moveMap.bind(keyboard, "ctrl 4", dropFourthSlot);
moveMap.bind(keyboard, "ctrl 5", dropFifthSlot);
moveMap.bind(keyboard, "ctrl 6", dropSixthSlot);
moveMap.bind(keyboard, "ctrl 7", dropSeventhSlot);
moveMap.bind(keyboard, "ctrl 8", dropEighthSlot);
moveMap.bind(keyboard, "ctrl 9", dropNinthSlot);
moveMap.bind(keyboard, "ctrl 0", dropTenthSlot);
moveMap.bind(keyboard, "ctrl a", openAdminWindow);
moveMap.bind(keyboard, "ctrl o", openOptionsWindow);
moveMap.bind(keyboard, "ctrl t", openMessageWindow);
moveMap.bind(keyboard, "ctrl d", openDeathmatchWindow);
moveMap.bind(keyboard, "ctrl w", toggleWrenchMode);
moveMap.bind(keyboard, "ctrl s", openPlayerWindow);
moveMap.bind(keyboard, "r", sit);
moveMap.bind(keyboard, "a", moveleft);
moveMap.bind(keyboard, "d", moveright);
moveMap.bind(keyboard, "numpadenter", plantBrick);
moveMap.bind(keyboard, "numpad0", cancelBrick);
moveMap.bind(keyboard, "i", IRCToggle);
moveMap.bind(keyboard, "f", FreeHands);
moveMap.bind(keyboard, "alt s", takeScreenShot);
moveMap.bind(keyboard, "numpad8", shiftBrickAway);
moveMap.bind(keyboard, "numpad2", shiftBrickTowards);
moveMap.bind(keyboard, "numpad4", shiftBrickleft);
moveMap.bind(keyboard, "numpad6", shiftBrickright);
moveMap.bind(keyboard, "+", shiftBrickup);
moveMap.bind(keyboard, "numpad5", shiftBrickdown);
moveMap.bind(keyboard, "numpad3", shiftBrickthirdup);
moveMap.bind(keyboard, "numpad1", shiftBrickthirddown);
moveMap.bind(keyboard, "numpad9", rotateBrickCW);
moveMap.bind(keyboard, "numpad7", rotateBrickCCW);
moveMap.bind(keyboard, "u", undoLast);
moveMap.bind(keyboard, "ralt", togTinyShift);
moveMap.bind(keyboard, "*", ScaleZPlus);
moveMap.bind(keyboard, "numpaddivide", ScaleZMinus);
moveMap.bind(keyboard, "lshift", crouch);
moveMap.bindCmd(keyboard, "ctrl v", "", "OpenClose(votinggui,pttagui);");
moveMap.bindCmd(keyboard, "ctrl c", "", "OpenClose(pttagui);");
moveMap.bind(keyboard, "left", turnLeft);
moveMap.bind(keyboard, "right", turnRight);
moveMap.bind(keyboard, "w", moveforward);
moveMap.bind(keyboard, "s", movebackward);
moveMap.bind(keyboard, "alt w", toggleWandMode);
moveMap.bind(keyboard, "x", ZoomIn);
moveMap.bind(keyboard, "alt 1", useSlot11);
moveMap.bind(keyboard, "alt 2", useSlot12);
moveMap.bind(keyboard, "alt 3", useSlot13);
moveMap.bind(keyboard, "alt 4", useSlot14);
moveMap.bind(keyboard, "alt 5", useSlot15);
moveMap.bind(keyboard, "alt 6", useSlot16);
moveMap.bind(keyboard, "alt 7", useSlot17);
moveMap.bind(keyboard, "alt 8", useSlot18);
moveMap.bind(keyboard, "alt 9", useSlot19);
moveMap.bind(keyboard, "alt 0", useSlot20);
moveMap.bind(keyboard, "ctrl-alt 1", dropSlot11);
moveMap.bind(keyboard, "ctrl-alt 2", dropSlot12);
moveMap.bind(keyboard, "ctrl-alt 3", dropSlot13);
moveMap.bind(keyboard, "ctrl-alt 4", dropSlot14);
moveMap.bind(keyboard, "ctrl-alt 5", dropSlot15);
moveMap.bind(keyboard, "ctrl-alt 6", dropSlot16);
moveMap.bind(keyboard, "ctrl-alt 7", dropSlot17);
moveMap.bind(keyboard, "ctrl-alt 8", dropSlot18);
moveMap.bind(keyboard, "ctrl-alt 9", dropSlot19);
moveMap.bind(keyboard, "ctrl-alt 0", dropSlot20);
moveMap.bind(keyboard, "ctrl r", cancelauto);
moveMap.bind(keyboard, "m", openBACsM);
moveMap.bind(keyboard, "j", WrenchM);
moveMap.bind(keyboard, "k", WandM);
moveMap.bind(keyboard, "ctrl numpad8", custommoveforward);
moveMap.bind(keyboard, "ctrl numpad2", custommovebackward);
moveMap.bind(keyboard, "ctrl numpad4", custommoveleft);
moveMap.bind(keyboard, "ctrl numpad6", custommoveright);
moveMap.bind(keyboard, "ctrl +", custommoveup);
moveMap.bind(keyboard, "ctrl numpad5", custommovedown);
moveMap.bind(keyboard, "ctrl numpad3", custommoveupsmall);
moveMap.bind(keyboard, "ctrl numpad1", custommovedownsmall);
moveMap.bind(keyboard, "ctrl numpad9", customrotzcw);
moveMap.bind(keyboard, "ctrl numpad7", customrotzccw);
moveMap.bind(keyboard, "alt numpad9", customrotxcw);
moveMap.bind(keyboard, "alt numpad7", customrotxccw);
moveMap.bind(keyboard, "ctrl-alt numpad9", customrotycw);
moveMap.bind(keyboard, "ctrl-alt numpad7", customrotyccw);
moveMap.bind(keyboard, "ctrl *", customscalezplus);
moveMap.bind(keyboard, "ctrl numpaddivide", customscalezminus);
moveMap.bind(keyboard, "alt *", customscalexplus);
moveMap.bind(keyboard, "alt numpaddivide", customscalexminus);
moveMap.bind(keyboard, "ctrl-alt *", customscaleyplus);
moveMap.bind(keyboard, "ctrl-alt numpaddivide", customscaleyminus);
moveMap.bind(keyboard, "ctrl home", shiftfavtog);
moveMap.bind(keyboard, "ctrl end", shiftfavrevtog);
moveMap.bind(keyboard, "alt home", rotfavtog);
moveMap.bind(keyboard, "alt end", rotfavrevtog);
moveMap.bind(keyboard, "ctrl-alt home", scalefavtog);
moveMap.bind(keyboard, "ctrl-alt end", scalefavrevtog);
moveMap.bind(keyboard, "lcontrol", toggleFreeLook);
moveMap.bind(keyboard, "numpaddecimal", openfactorset);
moveMap.bind(keyboard, "z", isbrickscroll);
moveMap.bind(keyboard, "ctrl m", RadarM);
moveMap.bind(mouse0, "xaxis", yaw);
moveMap.bind(mouse0, "yaxis", pitch);
moveMap.bind(mouse0, "button0", mouseFire);
moveMap.bind(mouse0, "button2", mouseWheelClick);
moveMap.bind(mouse0, "zaxis", handleMouseWheel);
moveMap.bind(mouse0, "button1", jet);
