// Torque Input Map File
movemap.delete();
new ActionMap(movemap);
movemap.bindCmd(keyboard, "escape", "", "escapeFromGame();");
movemap.bind(keyboard, "f3", startRecordingDemo);
movemap.bind(keyboard, "f4", stopRecordingDemo);
movemap.bind(keyboard, "alt o", openOptionsWindow);
movemap.bind(keyboard, "alt a", openAdminWindow);
movemap.bind(keyboard, "alt g", openiGobWindow);
movemap.bind(keyboard, "alt c", igobcopy);
movemap.bind(keyboard, "alt d", openDecalPalletWindow);
movemap.bind(keyboard, "alt p", Advancedprefstog);
movemap.bind(keyboard, "alt i", TBMPlayerOpGui);
movemap.bind(keyboard, "t", toggleMessageHud);
movemap.bind(keyboard, "pageup", pageMessageHudUp);
movemap.bind(keyboard, "pagedown", pageMessageHudDown);
movemap.bind(keyboard, "alt t", resizeMessageHud);
movemap.bind(keyboard, "alt h", ToggleHuds);
movemap.bind(keyboard, "w", moveforward);
movemap.bind(keyboard, "s", movebackward);
movemap.bind(keyboard, "a", moveleft);
movemap.bind(keyboard, "d", moveright);
movemap.bind(keyboard, "space", jump);
movemap.bind(keyboard, "c", togscan);
movemap.bind(keyboard, "lshift", crouch);
movemap.bind(keyboard, "f", toggleZoom);
movemap.bind(keyboard, "r", staticzoom);
movemap.bind(keyboard, "g", toggleigob);
movemap.bind(keyboard, "lcontrol", toggleFreeLook);
movemap.bind(keyboard, "tab", toggleFirstPerson);
movemap.bind(keyboard, "f8", dropCameraAtPlayer);
movemap.bind(keyboard, "f7", dropPlayerAtCamera);
movemap.bind(keyboard, "i", switchinv);
movemap.bind(keyboard, "z", togham);
movemap.bind(keyboard, "q", togsc);
movemap.bind(keyboard, "alt e", toggunedit);
movemap.bind(keyboard, "return", getinbuggy);
movemap.bind(keyboard, "delete", deleteselected);
movemap.bind(keyboard, "m", cspy);
movemap.bind(keyboard, "alt m", cspy1);
movemap.bind(keyboard, "numpad9", rotateBrickCW);
movemap.bind(keyboard, "numpad7", rotateBrickCCW);
movemap.bind(keyboard, "numpad8", shiftBrickAway);
movemap.bind(keyboard, "alt numpad8", sshiftBrickAway);
movemap.bind(keyboard, "numpad2", shiftBrickTowards);
movemap.bind(keyboard, "alt numpad2", sshiftBrickTowards);
movemap.bind(keyboard, "numpad4", shiftBrickLeft);
movemap.bind(keyboard, "alt numpad4", sshiftBrickLeft);
movemap.bind(keyboard, "numpad6", shiftBrickRight);
movemap.bind(keyboard, "alt numpad6", sshiftBrickRight);
movemap.bind(keyboard, "numpad3", shiftBrickThirdUp);
movemap.bind(keyboard, "+", shiftBrickUp);
movemap.bind(keyboard, "alt +", sshiftBrickUp);
movemap.bind(keyboard, "numpad1", shiftBrickThirdDown);
movemap.bind(keyboard, "numpad5", shiftBrickDown);
movemap.bind(keyboard, "alt numpad5", sshiftBrickDown);
movemap.bind(keyboard, "*", scaleup);
movemap.bind(keyboard, "alt *", sscaleup);
movemap.bind(keyboard, "numpadenter", plantBrick);
movemap.bind(keyboard, "numpad0", cancelBrick);
movemap.bind(keyboard, "1", useFirstSlot);
movemap.bind(keyboard, "2", useSecondSlot);
movemap.bind(keyboard, "3", useThirdSlot);
movemap.bind(keyboard, "4", useFourthSlot);
movemap.bind(keyboard, "5", useFifthSlot);
movemap.bind(keyboard, "6", useSixthSlot);
movemap.bind(keyboard, "7", useSeventhSlot);
movemap.bind(keyboard, "8", useEighthSlot);
movemap.bind(keyboard, "9", useNinthSlot);
movemap.bind(keyboard, "0", useTenthSlot);
movemap.bind(keyboard, "alt 1", dropFirstSlot);
movemap.bind(keyboard, "alt 2", dropSecondSlot);
movemap.bind(keyboard, "alt 3", dropThirdSlot);
movemap.bind(keyboard, "alt 4", dropFourthSlot);
movemap.bind(keyboard, "alt 5", dropFifthSlot);
movemap.bind(keyboard, "alt 6", dropSixthSlot);
movemap.bind(keyboard, "alt 7", dropSeventhSlot);
movemap.bind(keyboard, "alt 8", dropEighthSlot);
movemap.bind(keyboard, "alt 9", dropNinthSlot);
movemap.bind(keyboard, "alt 0", dropTenthSlot);
movemap.bind(keyboard, "alt j", togglejoinservergui);
movemap.bind(keyboard, "f2", playlisttog);
movemap.bind(keyboard, "alt f2", teamtog);
movemap.bind(keyboard, "alt k", suicide);
movemap.bind(keyboard, "alt x", igobcut);
movemap.bind(keyboard, "alt v", igobpaste);
movemap.bind(keyboard, "alt q", colorpl);
movemap.bind(keyboard, "insert", doScreenShot);
movemap.bind(keyboard, "x", togeyed);
movemap.bindCmd(keyboard, "j", "", "commandtoserver(\'EmoteQuestion\');");
movemap.bindCmd(keyboard, "k", "", "commandtoserver(\'EmoteExclaim\');");
movemap.bindCmd(keyboard, "l", "", "commandtoserver(\'EmoteLove\');");
movemap.bindCmd(keyboard, ";", "", "commandtoserver(\'EmoteAFK\');");
movemap.bind(keyboard, "e", togedit);
movemap.bind(keyboard, "numpaddivide", scaledown);
movemap.bind(keyboard, "alt numpaddivide", sscaledown);
movemap.bind(keyboard, "ralt", walk);
movemap.bind(keyboard, "left", turnLeft);
movemap.bind(keyboard, "right", turnRight);
movemap.bind(keyboard, "up", panup);
movemap.bind(keyboard, "down", pandown);
movemap.bind(keyboard, "alt s", togglesnipergui);
movemap.bind(mouse0, "xaxis", yaw);
movemap.bind(mouse0, "yaxis", pitch);
movemap.bind(mouse0, "button1", jet);
movemap.bind(mouse0, "zaxis", handleMouseWheel);
movemap.bind(mouse0, "button0", mouseFire);
movemap.bind(mouse0, "button2", SpecialOpGui);
movemap.bind(mouse0, "alt button2", caiguitog);
